{% set name = "foundry_ml" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/foundry_ml-{{ version }}.tar.gz
  sha256: 9f9cce3b9c2d00e56d613dafe7e58b5eaa81c230f01b73bc92ac6b58f8f015af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dlhub-sdk >=1.0.0
    - globus-sdk >=3,<4
    - h5py >=2.10.0
    - joblib >=1.0.0
    - json2table
    - mdf-connect-client >=0.4.0
    - mdf_forge >=0.8.0
    - numpy >=1.15.4
    - pandas >=0.23.4
    - pydantic >=1.4
    - python >=3.6

test:
  imports:
    - foundry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MLMI2-CSSI/foundry
  summary: Package to support simplified application of machine learning models to datasets in materials science
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - WardLT
    - jan-janssen
